# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    set -e
    curl https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2020-03/R/eclipse-rcp-2020-03-R-linux-gtk-x86_64.tar.gz&mirror_id=1045 -o eclipse.tar.gz
    tar -xzf "eclipse.tar.gz" -C "eclipse"
    eclipse/eclipse/eclipse -nosplash  -application org.eclipse.ant.core.antRunner -data .. -verbose -buildfile build.xml -DbuildTempFolder=build/temp -DbuildDirectory=build -Dbuild.result.folder=build/res -Dplugin.destination=build/plugin build.update.jar
  displayName: 'Build update jar'
- task: PublishBuildArtifacts@1
  displayName: 'Publish plugin JAR'
  inputs:
    pathtoPublish: build/plugin/saker.build.ide.eclipse.jar
    artifactName: saker.build.ide.eclipse.jar