trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: exit 1
  condition: eq(variables['RELEASE_VERSION'], '')
  displayName: 'Check RELEASE_VERSION variable'
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'saker.build.ide.eclipse-ci-release-push-2'
    userRepository: 'Sipkab/saker.build-site-ci-publish-test'
    defaultVersionType: 'specificTag'
    version: '$(RELEASE_VERSION)-saker.build.ide.eclipse'
    downloadPath: 'release-saker.build.ide.eclipse'
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'saker.build.ide.eclipse-ci-release-push-2'
    userRepository: 'Sipkab/saker.build-site-ci-publish-test'
    defaultVersionType: 'specificTag'
    version: '$(RELEASE_VERSION)-saker.java.ide.eclipse'
    downloadPath: 'release-saker.java.ide.eclipse'
